name: Trigger Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: "デプロイするブランチ"
        required: true
        default: "main"
        type: string

jobs:
  trigger:
    # PRがマージされた場合または手動実行の場合のみ実行
    if: github.event.pull_request.merged == true || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.INFRA_REPO_PAT }}
          repository: Shinogasa/Shinonome-doki-infra
          event-type: deploy-hugo
          client-payload: '{"branch": "${{ github.event.inputs.branch || github.ref_name }}"}'
